// Turns menu/menu.mjs into db/seed.sql.
// Run with: npm run seed:build
// The seed replaces the menu tables. It never touches orders.
import { writeFileSync } from 'node:fs';
import { menu, settings } from '../menu/menu.mjs';

const q = (v) => `'${String(v).replace(/'/g, "''")}'`;
const cents = (guilders) => Math.round(guilders * 100);

const out = [
  '-- Generated by scripts/build-seed.mjs. Do not edit by hand.',
  'DELETE FROM options;',
  'DELETE FROM option_groups;',
  'DELETE FROM items;',
  'DELETE FROM categories;',
];

let itemId = 0;
let groupId = 0;
let optionId = 0;

menu.forEach((cat, ci) => {
  const catId = ci + 1;
  out.push(
    `INSERT INTO categories (id, slug, name, note, sort) VALUES (${catId}, ${q(cat.slug)}, ${q(cat.name)}, ${q(cat.note || '')}, ${ci});`
  );
  cat.items.forEach((item, ii) => {
    itemId += 1;
    out.push(
      `INSERT INTO items (id, category_id, name, description, price_cents, image, alcohol, available, sort) VALUES (${itemId}, ${catId}, ${q(item.name)}, ${q(item.desc || '')}, ${cents(item.price || 0)}, ${q(item.image || '')}, ${item.alcohol ? 1 : 0}, 1, ${ii});`
    );
    (item.groups || []).forEach((group, gi) => {
      groupId += 1;
      out.push(
        `INSERT INTO option_groups (id, item_id, name, min_choices, max_choices, sort) VALUES (${groupId}, ${itemId}, ${q(group.name)}, ${group.min}, ${group.max}, ${gi});`
      );
      group.choices.forEach((choice, oi) => {
        optionId += 1;
        out.push(
          `INSERT INTO options (id, group_id, name, price_cents, alcohol, available, sort) VALUES (${optionId}, ${groupId}, ${q(choice.name)}, ${cents(choice.price || 0)}, ${choice.alcohol ? 1 : 0}, 1, ${oi});`
        );
      });
    });
  });
});

// Settings are only inserted when missing, so re-seeding keeps what staff changed.
for (const [key, value] of Object.entries(settings)) {
  out.push(`INSERT OR IGNORE INTO settings (key, value) VALUES (${q(key)}, ${q(JSON.stringify(value))});`);
}

writeFileSync(new URL('../db/seed.sql', import.meta.url), out.join('\n') + '\n');
console.log(`seed.sql written: ${menu.length} categories, ${itemId} items, ${groupId} option groups, ${optionId} options`);
